data:
  batch_size: 4
  num_workers: 0
  pin_memory: false
  resize: 224
  train_csv: /data1/open_data/seamless_interaction/preprocessed/train/clips.csv
  val_csv: null
  val_split: 0.2
device: cuda:0
experiment_name: debug_run
logger:
  log_interval: 50
loss:
  kwargs: {}
  name: global_clip
model: {}
optim:
  betas:
  - 0.9
  - 0.999
  lr: 3.0e-05
  weight_decay: 0.0
output_dir: runs/debug_run
seed: 123
train:
  amp: false
  epochs: 2
  grad_clip_norm: null
  val_every: 1
