experiment_name: "seamless_base"
seed: 42
device: "auto"        # "auto" | "cpu" | "cuda" | "cuda:0" | "cuda:2"
output_dir: "runs/seamless_base"

data:
  train_csv: "/data1/open_data/seamless_interaction/preprocessed/train/clips.csv"
  val_csv:   "/data1/open_data/seamless_interaction/preprocessed/val/clips.csv"   # or null to enable val_split
  val_split: 0.05   # used only if val_csv is null
  resize: 224
  batch_size: 4
  num_workers: 4
  pin_memory: false

model:
  # add kwargs your VideoFlowModel accepts, e.g.:
  # hidden_dim: 768
  # backbone_name: "timesformer"

optim:
  lr: 1.0e-5
  weight_decay: 0.01
  betas: [0.9, 0.999]

train:
  epochs: 30
  val_every: 1
  amp: true           # mixed precision if CUDA available
  grad_clip_norm: 1.0

loss:
  name: "global_clip"    # "global_clip" | "multimodal_alignment"
  temperature: 0.07      # used by global_clip_loss

logger:
  log_interval: 50
